# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  - name: serviceName
    value: fulfillment-service


steps:
  #- template: templates/include-steps.yml
  - bash: |
      commitAuthor=$(git log | head -4 | grep Author | awk -F '[:<]' '{print $2}' | sed 's/ //g' | tr A-Z a-z)
      if [[ $commitAuthor =~ "ebin" ]]; then
      commitAuthor="U02325RV7D1"
      elif [[ $commitAuthor =~ "alex" ]]; then
      commitAuthor="U027GEC49C6"
      elif [[ $commitAuthor =~ "simple" ]]; then
      commitAuthor="U023RP3A15W"
      fi
      echo '{"channel":"C050W5GADEH","text":"<@'${commitAuthor}'> build success. \n\n Service: ${{ variables.serviceName }}   Env: $(Build.SourceBranchName) \n\n Commit: $(Build.SourceVersionMessage)"}'
      
      buildUrl="$(System.TeamFoundationCollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)"
      echo buildUrl
      
      curl -X POST -H 'Content-type: application/json' \
      --data '{"text":"<@'${commitAuthor}'> build success. \n\n Service: ${{ variables.serviceName }}   Env: $(Build.SourceBranchName) \n\n Commit: $(Build.SourceVersionMessage)"}' \
      https://hooks.slack.com/services/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
#      curl -X POST -H 'Authorization: Bearer $(token)' \
#      -H 'Content-type: application/json' \
#        --data '{"channel":"C050W5GADEH","text":"<@'${commitAuthor}'> build success. \n\n Service: ${{ variables.serviceName }} Env: $(Build.SourceBranchName) \n\n Commit Message: $(Build.SourceVersionMessage)"}' \
#        https://slack.com/api/chat.postMessage

