# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  - name: serviceName
    value: fulfillment-service


steps:
  #- template: templates/include-steps.yml
  - bash: |
      commitAuthor=$(git log | head -4 | grep Author | awk -F '[:<]' '{print $2}' | sed 's/ //g')
      echo ${commitAuthor}
      echo "xx ${commitAuthor}"
      echo "'{"channel":"C050W5GADEH","text":"<@${commitAuthor}> ${{ variables.serviceName }} $(Build.SourceBranchName) $(Build.SourceVersionMessage) build success."}'"
#      curl -X POST -H 'Authorization: Bearer $(token)' \
#      -H 'Content-type: application/json' \
#        --data '{"channel":"C050W5GADEH","text":"<@$(commitAuthor)> ${{ variables.serviceName }} $(Build.SourceBranchName) $(Build.SourceVersionMessage) build success."}' \
#        https://slack.com/api/chat.postMessage

