name: build otel extension

on:
  push:
    branches: [ "release/*" ]

jobs:
  build-framework:
    uses: ebinsu/aliyun-action-templates/.github/workflows/docker-push-template.yml@main
    with:
      java_version: '17'
      java_cache: 'gradle'
      docker_image_name: 'core-framework/opentelemetry-javaagent'
      build_script: |
        gradle extendedAgent
    secrets: inherit